module.exports = {
	'/' 				: './routes/common_route',
	'/users'			: './routes/users_route',
	'/photo'			: './routes/photo_route',
	'/invitation'		: './routes/invitation_route',
	'/upload'			: './routes/upload_route',
	'/wechat'			: './routes/wechat_route',
	'/instructions'		: './routes/instruct_route',
	'/talk'				: './routes/talk_route',
    '/music' 			: './routes/music_route',
    '/towxy'			: './routes/wxy_route',
    '/tools'			: './routes/tools_route',

	'/blog/index'		: './routes/blogRoutes/index_blog_route',
	'/blog/mood'		: './routes/blogRoutes/mood_blog_route',
	'/blog/recollect'	: './routes/blogRoutes/recollect_blog_route',
	'/blog/about'		: './routes/blogRoutes/about_blog_route',
	'/blog/article'		: './routes/blogRoutes/article_blog_route',
	'/blog/way'			: './routes/blogRoutes/way_blog_route',
};