module.exports = {
	'/' 						: './routes/common_route',
    '/wechat'					: './routes/wechat/wechat_route',
	'/wechat/photo'				: './routes/wechat/photo_route',
	'/wechat/invitation'		: './routes/wechat/invitation_route',
	'/wechat/upload'			: './routes/wechat/upload_route',
	'/wechat/instructions'		: './routes/wechat/instruct_route',
	'/wechat/talk'				: './routes/wechat/talk_route',
    '/wechat/music' 			: './routes/wechat/music_route',
    '/wechat/towxy'				: './routes/wechat/wxy_route',
	'/wechat/auth'				: './routes/wechat/auth_route',
    '/wechat/tools'				: './routes/wechat/tools_route',

	'/blog'				: './routes/blog/index_blog_route',
	'/blog/mood'		: './routes/blog/mood_blog_route',
	'/blog/recollect'	: './routes/blog/recollect_blog_route',
	'/blog/personal'	: './routes/blog/about_blog_route',
	'/blog/article'		: './routes/blog/article_blog_route',
	'/blog/way'			: './routes/blog/way_blog_route',
};